version: '3'
services:
  bot_141:
    image: bot_141
    container_name: bot_141
    restart: always
    volumes:
      - /home/ubuntu/volumes/bot_141/sqlite/:/bot_root/bot/files
    environment:
      # Config
      - BASE_URL=wss://api.bale.ai/v1/bots/
      - TOKEN=da5b2817e583c88fa4a736d481693a6fcdbce700
      - SYSTEM_LOCAL=fa_IR
      - RESENDING_MAX_TRY=5
      - REUPLOADING_MAX_TRY=5
      # Log config
      - USE_GRAYLOG=0
      - LOG_SOURCE=bot_141
      - GRAYLOG_HOST=localhost
      - GRAYLOG_PORT=12201
      - LOG_LEVEL=20
      - LOG_FACILITY_NAME=bot_141